name = "firefly"
compatibility_date = "2026-05-10"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"

[[kv_namespaces]]
binding = "SESSION"
id = "4d8f9cbc7b7542078c8b1ba612ba8e13"

[vars]
NODE_VERSION = "22"